/* The following code was generated by JFlex 1.4.1 on 20/03/19 02:43 PM */


package Analizador;

import java.io.*;   
import javax.swing.text.Segment;   
   
import org.fife.ui.rsyntaxtextarea.*;   
   

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 20/03/19 02:43 PM from the specification file
 * <tt>ColoresFS.txt</tt>
 */
public class ColoresFS_1 extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int MLC = 1;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\7\1\0\1\6\23\0\1\6\1\43\1\4\1\0"+
    "\1\50\1\0\1\45\1\3\2\13\1\11\1\43\1\0\1\43\1\12"+
    "\1\10\12\2\1\46\1\0\1\43\1\47\1\0\1\43\1\0\1\21"+
    "\1\35\1\24\1\33\1\26\1\23\1\36\1\42\1\25\1\40\1\1"+
    "\1\16\1\30\1\14\1\17\1\31\1\37\1\22\1\32\1\27\1\15"+
    "\1\20\1\1\1\34\1\41\1\1\1\13\1\5\1\13\1\43\1\1"+
    "\1\0\1\21\1\35\1\24\1\33\1\26\1\23\1\36\1\42\1\25"+
    "\1\40\1\1\1\16\1\30\1\14\1\17\1\31\1\37\1\22\1\32"+
    "\1\27\1\15\1\20\1\1\1\34\1\41\1\1\1\13\1\44\1\13"+
    "\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\1\5\1\6\2\7"+
    "\1\1\1\10\16\1\1\7\1\11\1\12\1\11\1\0"+
    "\1\13\1\3\1\0\1\14\2\4\1\15\1\16\12\0"+
    "\14\1\1\17\4\1\1\0\1\2\1\20\1\21\14\0"+
    "\4\1\1\17\13\1\11\0\1\17\2\0\1\22\16\1"+
    "\15\0\15\1\11\0\10\1\13\0\4\1\14\0\2\1"+
    "\13\0\2\1\10\0\1\1\5\0\1\1\7\0\1\1"+
    "\5\0\1\1\5\0\1\1\5\0\1\1\2\0\1\1"+
    "\2\0\1\1\1\0\1\1\1\0\2\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[263];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\244\0\315\0\366\0\u011f"+
    "\0\122\0\u0148\0\122\0\u0171\0\122\0\u019a\0\u01c3\0\u01ec"+
    "\0\u0215\0\u023e\0\u0267\0\u0290\0\u02b9\0\u02e2\0\u030b\0\u0334"+
    "\0\u035d\0\u0386\0\u03af\0\u03d8\0\u0401\0\122\0\122\0\u042a"+
    "\0\122\0\u0453\0\u047c\0\122\0\u04a5\0\u04ce\0\u04f7\0\122"+
    "\0\u0520\0\u0549\0\u0572\0\u059b\0\u05c4\0\u05ed\0\u0616\0\u063f"+
    "\0\u0668\0\u0691\0\u06ba\0\u06e3\0\u070c\0\u0735\0\u075e\0\u0787"+
    "\0\u07b0\0\u07d9\0\u0802\0\u082b\0\u0854\0\u087d\0\u08a6\0\u08cf"+
    "\0\u08f8\0\u0921\0\u094a\0\u0973\0\u042a\0\122\0\122\0\u099c"+
    "\0\u09c5\0\u09ee\0\u0a17\0\u0a40\0\u0a69\0\u0a92\0\u0abb\0\u0ae4"+
    "\0\u0b0d\0\u0b36\0\u0b5f\0\u0b88\0\u0bb1\0\u0bda\0\u0c03\0\173"+
    "\0\u0c2c\0\u0c55\0\u0c7e\0\u0ca7\0\u0cd0\0\u0cf9\0\u0d22\0\u0d4b"+
    "\0\u0d74\0\u0d9d\0\u0dc6\0\u0def\0\u0e18\0\u0e41\0\u0e6a\0\u0e93"+
    "\0\u0ebc\0\u0ee5\0\u0f0e\0\u0f37\0\122\0\u0f60\0\u0f89\0\173"+
    "\0\u0fb2\0\u0fdb\0\u1004\0\u102d\0\u1056\0\u107f\0\u10a8\0\u10d1"+
    "\0\u10fa\0\u1123\0\u114c\0\u1175\0\u119e\0\u11c7\0\u11f0\0\u1219"+
    "\0\u1242\0\u126b\0\u1294\0\u12bd\0\u12e6\0\u130f\0\u1338\0\u1361"+
    "\0\u138a\0\u13b3\0\u13dc\0\u1405\0\u142e\0\u1457\0\u1480\0\u14a9"+
    "\0\u14d2\0\u14fb\0\u1524\0\u154d\0\u1576\0\u159f\0\u15c8\0\u15f1"+
    "\0\u161a\0\u1643\0\u166c\0\u1695\0\u16be\0\u16e7\0\u1710\0\u1739"+
    "\0\u1762\0\u178b\0\u17b4\0\u17dd\0\u1806\0\u182f\0\u1858\0\u1881"+
    "\0\u18aa\0\u18d3\0\u18fc\0\u1925\0\u194e\0\u1977\0\u19a0\0\u19c9"+
    "\0\u19f2\0\u1a1b\0\u1a44\0\u1a6d\0\u1a96\0\u1abf\0\u1ae8\0\u1b11"+
    "\0\u1b3a\0\u1b63\0\u1b8c\0\u1bb5\0\u1bde\0\u1c07\0\u1c30\0\u1c59"+
    "\0\u1c82\0\u1cab\0\u1cd4\0\u1cfd\0\u1d26\0\u1d4f\0\u1d78\0\u1da1"+
    "\0\u1dca\0\u1df3\0\u1e1c\0\u1e45\0\u1e6e\0\u1e97\0\u1ec0\0\u1ee9"+
    "\0\u1f12\0\u1f3b\0\u1f64\0\u1f8d\0\u1fb6\0\u1fdf\0\u2008\0\u2031"+
    "\0\u205a\0\u2083\0\u20ac\0\u20d5\0\u20fe\0\u2127\0\u2150\0\u2179"+
    "\0\u21a2\0\u21cb\0\u21f4\0\u221d\0\u2246\0\u226f\0\u2298\0\u22c1"+
    "\0\u22ea\0\u2313\0\u233c\0\u2365\0\u238e\0\u23b7\0\u23e0\0\u2409"+
    "\0\u2432\0\u245b\0\u2484\0\u24ad\0\u24d6\0\u24ff\0\u2528\0\u2551"+
    "\0\u257a\0\u25a3\0\u25cc\0\u25f5\0\u261e\0\u2647\0\u2670\0\u2699"+
    "\0\u26c2\0\u26eb\0\u2714\0\u273d\0\u2766\0\u278f\0\u27b8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[263];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\3\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\4\1\17\1\20"+
    "\1\21\1\4\1\22\1\23\1\24\1\25\3\4\1\26"+
    "\1\27\1\30\3\4\1\31\3\4\1\13\1\32\1\33"+
    "\1\34\1\13\1\3\7\35\1\36\40\35\1\37\52\0"+
    "\2\4\11\0\27\4\10\0\1\5\7\0\1\40\36\0"+
    "\3\6\1\41\1\6\1\42\1\6\1\43\41\6\4\7"+
    "\1\44\1\45\1\7\1\46\41\7\6\0\1\10\52\0"+
    "\1\47\1\50\56\0\1\51\1\0\1\52\1\53\1\54"+
    "\1\55\1\56\1\0\1\57\1\60\2\0\1\61\1\0"+
    "\1\62\14\0\2\4\11\0\1\4\1\63\25\4\7\0"+
    "\2\4\11\0\11\4\1\64\1\65\14\4\7\0\2\4"+
    "\11\0\4\4\1\66\22\4\7\0\2\4\11\0\5\4"+
    "\1\67\21\4\7\0\2\4\11\0\1\4\1\70\10\4"+
    "\1\71\14\4\7\0\2\4\11\0\1\4\1\72\25\4"+
    "\7\0\2\4\11\0\5\4\1\73\1\74\20\4\7\0"+
    "\2\4\11\0\14\4\1\75\12\4\7\0\2\4\11\0"+
    "\3\4\1\76\2\4\1\76\20\4\7\0\2\4\11\0"+
    "\11\4\1\77\1\100\1\101\13\4\7\0\2\4\11\0"+
    "\12\4\1\102\14\4\7\0\2\4\11\0\1\4\1\103"+
    "\25\4\52\0\1\13\51\0\1\13\52\0\1\104\1\0"+
    "\7\35\1\0\40\35\3\0\1\105\46\0\3\42\1\106"+
    "\3\42\1\0\41\42\3\43\1\41\1\43\1\0\43\43"+
    "\7\46\1\0\45\46\1\107\1\45\43\46\7\47\1\0"+
    "\41\47\35\0\1\110\31\0\1\111\13\0\1\112\44\0"+
    "\1\113\47\0\1\114\45\0\1\115\42\0\1\116\53\0"+
    "\1\117\52\0\1\120\3\0\1\121\51\0\1\122\37\0"+
    "\1\123\34\0\2\4\11\0\2\4\1\124\24\4\7\0"+
    "\2\4\11\0\1\125\26\4\7\0\2\4\11\0\12\4"+
    "\1\126\14\4\7\0\2\4\11\0\5\4\1\127\21\4"+
    "\7\0\2\4\11\0\6\4\1\130\20\4\7\0\2\4"+
    "\11\0\1\131\26\4\7\0\2\4\11\0\13\4\1\132"+
    "\13\4\7\0\2\4\11\0\1\133\26\4\7\0\2\4"+
    "\11\0\16\4\1\124\10\4\7\0\2\4\11\0\12\4"+
    "\1\134\14\4\7\0\2\4\11\0\15\4\1\135\11\4"+
    "\7\0\2\4\11\0\11\4\1\136\15\4\7\0\2\4"+
    "\11\0\1\124\26\4\7\0\2\4\11\0\2\4\1\137"+
    "\24\4\7\0\2\4\11\0\6\4\1\140\20\4\7\0"+
    "\2\4\11\0\7\4\1\141\3\4\1\142\13\4\7\0"+
    "\2\4\11\0\5\4\1\143\21\4\54\0\1\13\31\0"+
    "\1\144\45\0\1\145\11\0\1\146\36\0\1\147\57\0"+
    "\1\150\33\0\1\151\60\0\1\152\42\0\1\153\63\0"+
    "\1\154\46\0\1\155\2\0\1\156\30\0\1\156\66\0"+
    "\1\112\50\0\1\157\17\0\2\4\11\0\3\4\1\130"+
    "\23\4\7\0\2\4\11\0\12\4\1\160\14\4\7\0"+
    "\2\4\11\0\6\4\1\161\20\4\7\0\2\4\11\0"+
    "\2\4\1\160\24\4\7\0\2\4\11\0\14\4\1\162"+
    "\2\4\1\163\7\4\7\0\2\4\11\0\3\4\1\164"+
    "\23\4\7\0\2\4\11\0\10\4\1\165\16\4\7\0"+
    "\2\4\11\0\5\4\1\166\21\4\7\0\2\4\11\0"+
    "\3\4\1\167\2\4\1\170\20\4\7\0\2\4\11\0"+
    "\1\171\26\4\7\0\2\4\11\0\12\4\1\172\14\4"+
    "\7\0\2\4\11\0\11\4\1\173\15\4\7\0\2\4"+
    "\11\0\12\4\1\174\14\4\7\0\2\4\11\0\12\4"+
    "\1\175\14\4\7\0\2\4\11\0\17\4\1\176\7\4"+
    "\34\0\1\177\40\0\1\200\2\0\1\201\4\0\1\202"+
    "\37\0\1\203\61\0\1\204\37\0\1\205\62\0\1\206"+
    "\42\0\1\207\55\0\1\210\41\0\1\211\56\0\1\212"+
    "\47\0\1\213\25\0\2\4\11\0\22\4\1\214\4\4"+
    "\7\0\2\4\11\0\1\4\1\215\25\4\7\0\2\4"+
    "\11\0\5\4\1\216\21\4\7\0\2\4\11\0\6\4"+
    "\1\217\20\4\7\0\2\4\11\0\11\4\1\220\15\4"+
    "\7\0\2\4\11\0\6\4\1\221\20\4\7\0\2\4"+
    "\11\0\6\4\1\222\20\4\7\0\2\4\11\0\11\4"+
    "\1\223\15\4\7\0\2\4\11\0\13\4\1\160\13\4"+
    "\7\0\2\4\11\0\10\4\1\224\16\4\7\0\2\4"+
    "\11\0\1\225\26\4\7\0\2\4\11\0\10\4\1\226"+
    "\16\4\7\0\2\4\11\0\1\227\26\4\7\0\2\4"+
    "\11\0\6\4\1\230\20\4\22\0\1\231\61\0\1\232"+
    "\45\0\1\233\50\0\1\206\42\0\1\234\50\0\1\235"+
    "\60\0\1\236\46\0\1\213\50\0\1\237\50\0\1\240"+
    "\60\0\1\155\46\0\1\234\41\0\1\241\30\0\2\4"+
    "\11\0\20\4\1\242\6\4\7\0\2\4\11\0\2\4"+
    "\1\243\24\4\7\0\2\4\11\0\16\4\1\244\10\4"+
    "\7\0\2\4\11\0\1\21\26\4\7\0\2\4\11\0"+
    "\3\4\1\245\23\4\7\0\2\4\11\0\5\4\1\246"+
    "\21\4\7\0\2\4\11\0\13\4\1\21\13\4\7\0"+
    "\2\4\11\0\14\4\1\247\12\4\7\0\2\4\11\0"+
    "\10\4\1\250\16\4\7\0\2\4\11\0\22\4\1\160"+
    "\4\4\7\0\2\4\11\0\13\4\1\124\13\4\7\0"+
    "\2\4\11\0\12\4\1\67\14\4\7\0\2\4\11\0"+
    "\5\4\1\251\21\4\34\0\1\252\46\0\1\155\62\0"+
    "\1\213\31\0\1\155\64\0\1\253\43\0\1\155\42\0"+
    "\1\254\1\255\1\256\1\0\1\257\1\260\1\0\1\261"+
    "\3\0\1\262\1\0\1\263\42\0\1\264\43\0\1\155"+
    "\27\0\2\4\11\0\14\4\1\265\12\4\7\0\2\4"+
    "\11\0\13\4\1\266\13\4\7\0\2\4\11\0\14\4"+
    "\1\160\12\4\7\0\2\4\11\0\1\130\26\4\7\0"+
    "\2\4\11\0\6\4\1\267\20\4\7\0\2\4\11\0"+
    "\11\4\1\67\15\4\7\0\2\4\11\0\11\4\1\270"+
    "\15\4\7\0\2\4\11\0\13\4\1\125\13\4\30\0"+
    "\1\271\54\0\1\272\47\0\1\273\1\274\44\0\1\275"+
    "\54\0\1\276\41\0\1\277\1\0\1\300\57\0\1\301"+
    "\46\0\1\302\50\0\1\303\41\0\1\304\56\0\1\241"+
    "\24\0\2\4\11\0\2\4\1\130\24\4\7\0\2\4"+
    "\11\0\17\4\1\163\7\4\7\0\2\4\11\0\6\4"+
    "\1\305\20\4\7\0\2\4\11\0\3\4\1\306\23\4"+
    "\37\0\1\307\33\0\1\310\67\0\1\311\31\0\1\312"+
    "\62\0\1\313\53\0\1\314\33\0\1\315\74\0\1\313"+
    "\31\0\1\316\63\0\1\317\46\0\1\320\45\0\1\321"+
    "\22\0\2\4\11\0\5\4\1\322\21\4\7\0\2\4"+
    "\11\0\1\323\26\4\25\0\1\324\60\0\1\236\47\0"+
    "\1\234\51\0\1\325\42\0\1\326\51\0\1\327\55\0"+
    "\1\330\57\0\1\331\41\0\1\234\52\0\1\332\36\0"+
    "\1\333\32\0\2\4\11\0\25\4\1\334\1\4\7\0"+
    "\2\4\11\0\5\4\1\130\21\4\30\0\1\335\47\0"+
    "\1\336\56\0\1\261\40\0\1\337\53\0\1\340\54\0"+
    "\1\333\40\0\1\341\46\0\1\155\35\0\2\4\11\0"+
    "\17\4\1\342\7\4\22\0\1\343\10\0\1\344\1\345"+
    "\36\0\1\346\67\0\1\347\34\0\1\350\57\0\1\351"+
    "\23\0\2\4\11\0\12\4\1\352\14\4\25\0\1\353"+
    "\64\0\1\155\44\0\1\354\42\0\1\155\44\0\1\355"+
    "\51\0\1\356\70\0\1\357\13\0\2\4\11\0\16\4"+
    "\1\360\10\4\36\0\1\361\45\0\1\362\47\0\1\363"+
    "\40\0\1\364\55\0\1\365\30\0\2\4\11\0\17\4"+
    "\1\366\7\4\43\0\1\367\52\0\1\370\40\0\1\371"+
    "\36\0\1\372\70\0\1\373\14\0\2\4\11\0\12\4"+
    "\1\374\14\4\30\0\1\236\43\0\1\375\52\0\1\241"+
    "\61\0\1\376\36\0\1\236\33\0\2\4\11\0\5\4"+
    "\1\377\21\4\34\0\1\u0100\50\0\1\u0101\23\0\2\4"+
    "\11\0\6\4\1\u0102\20\4\35\0\1\346\43\0\1\u0103"+
    "\27\0\2\4\11\0\10\4\1\u0104\16\4\33\0\1\u0105"+
    "\24\0\2\4\11\0\26\4\1\u0106\32\0\1\234\25\0"+
    "\2\4\11\0\11\4\1\u0107\15\4\7\0\2\4\11\0"+
    "\4\4\1\124\22\4\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10209];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\5\1\1\11\1\1\1\11\1\1\1\11"+
    "\20\1\2\11\1\0\1\11\1\1\1\0\1\11\3\1"+
    "\1\11\12\0\21\1\1\0\1\1\2\11\14\0\20\1"+
    "\11\0\1\11\2\0\17\1\15\0\15\1\11\0\10\1"+
    "\13\0\4\1\14\0\2\1\13\0\2\1\10\0\1\1"+
    "\5\0\1\1\7\0\1\1\5\0\1\1\5\0\1\1"+
    "\5\0\1\1\2\0\1\1\2\0\1\1\1\0\1\1"+
    "\1\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[263];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
   
   /**   
    * Constructor.  This must be here because JFlex does not generate a   
    * no-parameter constructor.   
    */   
   public ColoresFS_1() {  }
 
      
   
   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param tokenType The token's type.   
    * @see #addToken(int, int, int)   
    */   
   private void addHyperlinkToken(int start, int end, int tokenType) {   
      int so = start + offsetShift;   
      addToken(zzBuffer, start,end, tokenType, so, true);   
   }   
   
   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param tokenType The token's type.   
    */   
   private void addToken(int tokenType) {   
      addToken(zzStartRead, zzMarkedPos-1, tokenType);   
   }   
   
   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param tokenType The token's type.   
    * @see #addHyperlinkToken(int, int, int)   
    */   
   private void addToken(int start, int end, int tokenType) {   
      int so = start + offsetShift;   
      addToken(zzBuffer, start,end, tokenType, so, false);   
   }   
   
   /**   
    * Adds the token specified to the current linked list of tokens.   
    *   
    * @param array The character array.   
    * @param start The starting offset in the array.   
    * @param end The ending offset in the array.   
    * @param tokenType The token's type.   
    * @param startOffset The offset in the document at which this token   
    *        occurs.   
    * @param hyperlink Whether this token is a hyperlink.   
    */   
   public void addToken(char[] array, int start, int end, int tokenType,   
                  int startOffset, boolean hyperlink) {   
      super.addToken(array, start,end, tokenType, startOffset, hyperlink);   
      zzStartRead = zzMarkedPos;   
   }   
   
   /**   
    * Returns the text to place at the beginning and end of a   
    * line to "comment" it in a this programming language.   
    *   
    * @return The start and end strings to add to a line to "comment"   
    *         it out.   
    */   
   public String[] getLineCommentStartAndEnd() {   
      return new String[] { "//", null };   
   }   
   
   /**   
    * Returns the first token in the linked list of tokens generated   
    * from <code>text</code>.  This method must be implemented by   
    * subclasses so they can correctly implement syntax highlighting.   
    *   
    * @param text The text from which to get tokens.   
    * @param initialTokenType The token type we should start with.   
    * @param startOffset The offset into the document at which   
    *        <code>text</code> starts.   
    * @return The first <code>Token</code> in a linked list representing   
    *         the syntax highlighted text.   
    */   
   public Token getTokenList(Segment text, int initialTokenType, int startOffset) {   
   
      resetTokenList();   
      this.offsetShift = -text.offset + startOffset;   
   
      // Start off in the proper state.   
      int state = Token.NULL;   
      switch (initialTokenType) {   
                  case Token.COMMENT_MULTILINE:   
            state = MLC;   
            start = text.offset;   
            break;   
   
         /* No documentation comments */   
         default:   
            state = Token.NULL;   
      }   
   
      s = text;   
      try {   
         yyreset(zzReader);   
         yybegin(state);   
         return yylex();   
      } catch (IOException ioe) {   
         ioe.printStackTrace();   
         return new TokenImpl();   
      }   
   
   }   
   
   /**   
    * Refills the input buffer.   
    *   
    * @return      <code>true</code> if EOF was reached, otherwise   
    *              <code>false</code>.   
    */   
   private boolean zzRefill() {   
//este se queda
      return zzCurrentPos>=s.offset+s.count;   
   }   
   

   
   /**   
    * Resets the scanner to read from a new input stream.   
    * Does not close the old reader.   
    *   
    * All internal variables are reset, the old input stream    
    * <b>cannot</b> be reused (internal buffer is discarded and lost).   
    * Lexical state is set to <tt>YY_INITIAL</tt>.   
    *   
    * @param reader   the new input stream    
    */   
   public final void yyreset(Reader reader) {  



//este se queda 
      // 's' has been updated.   
      zzBuffer = s.array;   
      /*   
       * We replaced the line below with the two below it because zzRefill   
       * no longer "refills" the buffer (since the way we do it, it's always   
       * "full" the first time through, since it points to the segment's   
       * array).  So, we assign zzEndRead here.   
       */   
      //zzStartRead = zzEndRead = s.offset;   
      zzStartRead = s.offset;   
      zzEndRead = zzStartRead + s.count - 1;   
      zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;   
      zzLexicalState = YYINITIAL;   
      zzReader = reader;   
      zzAtBOL  = true;   
      zzAtEOF  = false;   
   }   
   


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ColoresFS_1(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ColoresFS_1(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 182) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
    

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }




  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 6: 
          { addNullToken(); return firstToken;
          }
        case 19: break;
        case 11: 
          { addToken(Token.LITERAL_CHAR);
          }
        case 20: break;
        case 14: 
          { start = zzMarkedPos-2; yybegin(MLC);
          }
        case 21: break;
        case 5: 
          { addToken(Token.WHITESPACE);
          }
        case 22: break;
        case 17: 
          { addToken(Token.ERROR_STRING_DOUBLE);
          }
        case 23: break;
        case 15: 
          { addToken(Token.RESERVED_WORD);
          }
        case 24: break;
        case 8: 
          { addToken(Token.SEPARATOR);
          }
        case 25: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 26: break;
        case 18: 
          { addToken(Token.FUNCTION);
          }
        case 27: break;
        case 3: 
          { addToken(Token.ERROR_CHAR); addNullToken(); return firstToken;
          }
        case 28: break;
        case 4: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 29: break;
        case 16: 
          { addToken(Token.ERROR_CHAR);
          }
        case 30: break;
        case 12: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 31: break;
        case 13: 
          { addToken(Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 32: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 33: break;
        case 7: 
          { addToken(Token.OPERATOR);
          }
        case 34: break;
        case 9: 
          { 
          }
        case 35: break;
        case 10: 
          { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
          }
        case 36: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 264: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 265: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
