
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package GramaticaFlexYCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 14;
  public static final int coma = 10;
  public static final int por = 7;
  public static final int parenI = 12;
  public static final int parenD = 13;
  public static final int numerico = 3;
  public static final int menos = 6;
  public static final int pComa = 9;
  public static final int modular = 16;
  public static final int igual = 4;
  public static final int EOF = 0;
  public static final int division = 8;
  public static final int potencia = 17;
  public static final int error = 1;
  public static final int entero = 2;
  public static final int mas = 5;
  public static final int dosPuntos = 11;
  public static final int iden = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "numerico",
  "igual",
  "mas",
  "menos",
  "por",
  "division",
  "pComa",
  "coma",
  "dosPuntos",
  "parenI",
  "parenD",
  "cadena",
  "iden",
  "modular",
  "potencia"
  };
}

