
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package GramaticaFlexYCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menorigual = 23;
  public static final int cadena = 14;
  public static final int not = 20;
  public static final int coma = 10;
  public static final int True = 18;
  public static final int por = 7;
  public static final int parenI = 12;
  public static final int or = 27;
  public static final int False = 19;
  public static final int parenD = 13;
  public static final int numerico = 3;
  public static final int menos = 6;
  public static final int pComa = 9;
  public static final int mayorigual = 24;
  public static final int modular = 16;
  public static final int menorque = 25;
  public static final int igual = 4;
  public static final int EOF = 0;
  public static final int division = 8;
  public static final int noigual = 22;
  public static final int potencia = 17;
  public static final int mayorque = 26;
  public static final int cori = 30;
  public static final int error = 1;
  public static final int entero = 2;
  public static final int cord = 31;
  public static final int mas = 5;
  public static final int dosPuntos = 11;
  public static final int preg = 29;
  public static final int igualigual = 21;
  public static final int and = 28;
  public static final int iden = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "numerico",
  "igual",
  "mas",
  "menos",
  "por",
  "division",
  "pComa",
  "coma",
  "dosPuntos",
  "parenI",
  "parenD",
  "cadena",
  "iden",
  "modular",
  "potencia",
  "True",
  "False",
  "not",
  "igualigual",
  "noigual",
  "menorigual",
  "mayorigual",
  "menorque",
  "mayorque",
  "or",
  "and",
  "preg",
  "cori",
  "cord"
  };
}

