
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package GramaticaFlexYCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int In = 43;
  public static final int igualigual = 23;
  public static final int True = 18;
  public static final int Null = 44;
  public static final int If = 34;
  public static final int dosPuntos = 11;
  public static final int Default = 45;
  public static final int coma = 10;
  public static final int igual = 4;
  public static final int Else = 37;
  public static final int Break = 21;
  public static final int llavei = 35;
  public static final int llaved = 36;
  public static final int mayorque = 28;
  public static final int Return = 39;
  public static final int iden = 15;
  public static final int pComa = 9;
  public static final int While = 40;
  public static final int menos = 6;
  public static final int For = 42;
  public static final int cori = 32;
  public static final int EOF = 0;
  public static final int mas = 5;
  public static final int Function = 38;
  public static final int cord = 33;
  public static final int error = 1;
  public static final int Switch = 46;
  public static final int False = 19;
  public static final int entero = 2;
  public static final int or = 29;
  public static final int menorigual = 25;
  public static final int por = 7;
  public static final int Do = 22;
  public static final int menorque = 27;
  public static final int Continue = 41;
  public static final int Case = 47;
  public static final int potencia = 17;
  public static final int numerico = 3;
  public static final int parenI = 12;
  public static final int preg = 31;
  public static final int parenD = 13;
  public static final int noigual = 24;
  public static final int mayorigual = 26;
  public static final int and = 30;
  public static final int not = 20;
  public static final int modular = 16;
  public static final int division = 8;
  public static final int cadena = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "numerico",
  "igual",
  "mas",
  "menos",
  "por",
  "division",
  "pComa",
  "coma",
  "dosPuntos",
  "parenI",
  "parenD",
  "cadena",
  "iden",
  "modular",
  "potencia",
  "True",
  "False",
  "not",
  "Break",
  "Do",
  "igualigual",
  "noigual",
  "menorigual",
  "mayorigual",
  "menorque",
  "mayorque",
  "or",
  "and",
  "preg",
  "cori",
  "cord",
  "If",
  "llavei",
  "llaved",
  "Else",
  "Function",
  "Return",
  "While",
  "Continue",
  "For",
  "In",
  "Null",
  "Default",
  "Switch",
  "Case"
  };
}

