/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
/** Analizador de expresiones aritmeticas sencillas. */
package GramaticaJavaCC;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO = 7;
  /** RegularExpression Id. */
  int DECIMAL = 8;
  /** RegularExpression Id. */
  int ENTERO = 9;
  /** RegularExpression Id. */
  int CADENA = 10;
  /** RegularExpression Id. */
  int TRUE = 11;
  /** RegularExpression Id. */
  int FALSE = 12;
  /** RegularExpression Id. */
  int IMPRIMIR = 13;
  /** RegularExpression Id. */
  int MIENTRAS = 14;
  /** RegularExpression Id. */
  int FOR = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int FUNCION = 17;
  /** RegularExpression Id. */
  int RETORNO = 18;
  /** RegularExpression Id. */
  int BREAK = 19;
  /** RegularExpression Id. */
  int CONTINUE = 20;
  /** RegularExpression Id. */
  int IN = 21;
  /** RegularExpression Id. */
  int SI = 22;
  /** RegularExpression Id. */
  int SINO = 23;
  /** RegularExpression Id. */
  int PCOMA = 24;
  /** RegularExpression Id. */
  int DOSPUNTOS = 25;
  /** RegularExpression Id. */
  int PARENI = 26;
  /** RegularExpression Id. */
  int PAREND = 27;
  /** RegularExpression Id. */
  int CORI = 28;
  /** RegularExpression Id. */
  int CORD = 29;
  /** RegularExpression Id. */
  int LLAVEI = 30;
  /** RegularExpression Id. */
  int LLAVED = 31;
  /** RegularExpression Id. */
  int MAS = 32;
  /** RegularExpression Id. */
  int PREG = 33;
  /** RegularExpression Id. */
  int MENOS = 34;
  /** RegularExpression Id. */
  int POR = 35;
  /** RegularExpression Id. */
  int DIV = 36;
  /** RegularExpression Id. */
  int IGUAL = 37;
  /** RegularExpression Id. */
  int MENORQUE = 38;
  /** RegularExpression Id. */
  int MAYORQUE = 39;
  /** RegularExpression Id. */
  int MENORIGUAL = 40;
  /** RegularExpression Id. */
  int MAYORIGUAL = 41;
  /** RegularExpression Id. */
  int IGUALACION = 42;
  /** RegularExpression Id. */
  int DIFERENCIACION = 43;
  /** RegularExpression Id. */
  int COMA = 44;
  /** RegularExpression Id. */
  int AND = 45;
  /** RegularExpression Id. */
  int OR = 46;
  /** RegularExpression Id. */
  int NOT = 47;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 48;
  /** RegularExpression Id. */
  int STRING = 51;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<NUMERO>",
    "<DECIMAL>",
    "\"Numero\"",
    "\"Cadena\"",
    "\"true\"",
    "\"false\"",
    "\"print\"",
    "\"while\"",
    "\"for\"",
    "\"do\"",
    "\"Funcion\"",
    "\"Return\"",
    "\"Break\"",
    "\"continue\"",
    "\"in\"",
    "\"if\"",
    "\"else\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"?\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\",\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<IDENTIFICADOR>",
    "\"\\\"\"",
    "<token of kind 50>",
    "\"\\\"\"",
  };

}
