/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
/** Analizador de expresiones aritmeticas sencillas. */
package GramaticaJavaCC;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO = 7;
  /** RegularExpression Id. */
  int DECIMAL = 8;
  /** RegularExpression Id. */
  int NULL = 9;
  /** RegularExpression Id. */
  int TRUE = 10;
  /** RegularExpression Id. */
  int FALSE = 11;
  /** RegularExpression Id. */
  int MIENTRAS = 12;
  /** RegularExpression Id. */
  int CASE = 13;
  /** RegularExpression Id. */
  int SWITCH = 14;
  /** RegularExpression Id. */
  int FOR = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int SDEFAULT = 17;
  /** RegularExpression Id. */
  int FUNCION = 18;
  /** RegularExpression Id. */
  int RETORNO = 19;
  /** RegularExpression Id. */
  int BREAK = 20;
  /** RegularExpression Id. */
  int CONTINUE = 21;
  /** RegularExpression Id. */
  int IN = 22;
  /** RegularExpression Id. */
  int SI = 23;
  /** RegularExpression Id. */
  int SINO = 24;
  /** RegularExpression Id. */
  int PCOMA = 25;
  /** RegularExpression Id. */
  int DOSPUNTOS = 26;
  /** RegularExpression Id. */
  int PARENI = 27;
  /** RegularExpression Id. */
  int PAREND = 28;
  /** RegularExpression Id. */
  int CORI = 29;
  /** RegularExpression Id. */
  int CORD = 30;
  /** RegularExpression Id. */
  int LLAVEI = 31;
  /** RegularExpression Id. */
  int LLAVED = 32;
  /** RegularExpression Id. */
  int MODULO = 33;
  /** RegularExpression Id. */
  int POTENCIA = 34;
  /** RegularExpression Id. */
  int MAS = 35;
  /** RegularExpression Id. */
  int PREG = 36;
  /** RegularExpression Id. */
  int MENOS = 37;
  /** RegularExpression Id. */
  int POR = 38;
  /** RegularExpression Id. */
  int DIV = 39;
  /** RegularExpression Id. */
  int IGUAL = 40;
  /** RegularExpression Id. */
  int MENORQUE = 41;
  /** RegularExpression Id. */
  int MAYORQUE = 42;
  /** RegularExpression Id. */
  int MENORIGUAL = 43;
  /** RegularExpression Id. */
  int MAYORIGUAL = 44;
  /** RegularExpression Id. */
  int IGUALACION = 45;
  /** RegularExpression Id. */
  int DIFERENCIACION = 46;
  /** RegularExpression Id. */
  int COMA = 47;
  /** RegularExpression Id. */
  int AND = 48;
  /** RegularExpression Id. */
  int OR = 49;
  /** RegularExpression Id. */
  int NOT = 50;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 51;
  /** RegularExpression Id. */
  int STRING = 54;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<NUMERO>",
    "<DECIMAL>",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"case\"",
    "\"switch\"",
    "\"for\"",
    "\"do\"",
    "\"default\"",
    "\"function\"",
    "\"Return\"",
    "\"Break\"",
    "\"continue\"",
    "\"in\"",
    "\"if\"",
    "\"else\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"%%\"",
    "\"^\"",
    "\"+\"",
    "\"?\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\",\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<IDENTIFICADOR>",
    "\"\\\"\"",
    "<token of kind 53>",
    "\"\\\"\"",
  };

}
