/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
/** Analizador de expresiones aritmeticas sencillas. */
package GramaticaJavaCC;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO = 7;
  /** RegularExpression Id. */
  int DECIMAL = 8;
  /** RegularExpression Id. */
  int TRUE = 9;
  /** RegularExpression Id. */
  int FALSE = 10;
  /** RegularExpression Id. */
  int MIENTRAS = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int FUNCION = 14;
  /** RegularExpression Id. */
  int RETORNO = 15;
  /** RegularExpression Id. */
  int BREAK = 16;
  /** RegularExpression Id. */
  int CONTINUE = 17;
  /** RegularExpression Id. */
  int IN = 18;
  /** RegularExpression Id. */
  int SI = 19;
  /** RegularExpression Id. */
  int SINO = 20;
  /** RegularExpression Id. */
  int PCOMA = 21;
  /** RegularExpression Id. */
  int DOSPUNTOS = 22;
  /** RegularExpression Id. */
  int PARENI = 23;
  /** RegularExpression Id. */
  int PAREND = 24;
  /** RegularExpression Id. */
  int CORI = 25;
  /** RegularExpression Id. */
  int CORD = 26;
  /** RegularExpression Id. */
  int LLAVEI = 27;
  /** RegularExpression Id. */
  int LLAVED = 28;
  /** RegularExpression Id. */
  int MAS = 29;
  /** RegularExpression Id. */
  int PREG = 30;
  /** RegularExpression Id. */
  int MENOS = 31;
  /** RegularExpression Id. */
  int POR = 32;
  /** RegularExpression Id. */
  int DIV = 33;
  /** RegularExpression Id. */
  int IGUAL = 34;
  /** RegularExpression Id. */
  int MENORQUE = 35;
  /** RegularExpression Id. */
  int MAYORQUE = 36;
  /** RegularExpression Id. */
  int MENORIGUAL = 37;
  /** RegularExpression Id. */
  int MAYORIGUAL = 38;
  /** RegularExpression Id. */
  int IGUALACION = 39;
  /** RegularExpression Id. */
  int DIFERENCIACION = 40;
  /** RegularExpression Id. */
  int COMA = 41;
  /** RegularExpression Id. */
  int AND = 42;
  /** RegularExpression Id. */
  int OR = 43;
  /** RegularExpression Id. */
  int NOT = 44;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 45;
  /** RegularExpression Id. */
  int STRING = 48;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<NUMERO>",
    "<DECIMAL>",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"for\"",
    "\"do\"",
    "\"function\"",
    "\"Return\"",
    "\"Break\"",
    "\"continue\"",
    "\"in\"",
    "\"if\"",
    "\"else\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"?\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\",\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<IDENTIFICADOR>",
    "\"\\\"\"",
    "<token of kind 47>",
    "\"\\\"\"",
  };

}
